version: '3.3'

services:

#    volumes:
#      - ./volumes/auth:/usr/local/etc/gotrue/
#

  rest:
    container_name: supabase-rest
    image: postgrest/postgrest:v9.0.0
    depends_on:
      - db
    restart: unless-stopped
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@db:5433/postgres
      PGRST_DB_SCHEMAS: public,storage, graphql_public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${JWT_SECRET}
      PGRST_DB_USE_LEGACY_GUCS: "false"


  db:
    image: yugabytedb/yugabyte:latest
    command:  bin/yugabyted start --daemon=false --initial_scripts_dir /docker-entrypoint-initdb.d
    restart: always
    ports:
      - "5433:5433"
    environment:
      YSQL_DB: db
    volumes:
      - ./volumes/db/init:/docker-entrypoint-initdb.d/
